### ISSUE TITLE
App Crashes on Startup

### ISSUE THREAD

**Issue by cristianrosu** [KyteApp/react-native-helpcrunch#2]
The app crashes when I add `<RNHelpCrunch />` into a screen. Only tested it on IOS. Could you share some docs on how to use this plugin?

**Comment by ital0** [comment]
@cristianrosu sorry, I remember to see your message, but probably I forgot to answer you due to tons of work to do.
Unfornately I can't write this documentation because there's no time for that, but I'll list for you some methods. Please, try and see if helps you.

`HelpCrunch.init(organization, applicationId, applicationSecret, registerForNotifications = false, preChatFields = null, packageName = null)`

This will initialize HelpCrunch, in background, and will set the module ready to use.

`HelpCrunch.updateUser({ userId, userName, userEmail, customData })`

This will update the current user using your app. In short, it will be this information that you will see in the HelpCrunch dashboard.

`HelpCrunch.showChat()`

This will open that chat window.

`HelpCrunch.setThemeConfiguration()`

So, this method is a little bit of workaround. For iOS, you could pass some keys (available at HelpCrunch docs) and set colors, texts, etc. But for Android you gotta add those keys at `android/app/src/main/res/values/strings.xml`...

`HelpCrunch.trackEvent(eventName, eventProps = null)`

This will record an event in your user's information at HelpCrunch panel.

`HelpCrunch.logout()`

This will logout the current user that you previously sent their informations.

`HelpCrunch.addListener(eventType, callback = null)`

This will add a listener to HelpCrunch. The available listeners are:

**HCSURLNotification
HCSImageURLNotification
HCSFileURLNotification
HCSUserStartedChatNotification
HCSUserClosedChatNotification
HCSUnreadChatsNotification**

Please, go to HelpCrunch docs to get more info about this.

`HelpCrunch.removeListener(eventType)`

This will remove the previous listener added.

`HelpCrunch.getNumberOfUnreadChats()`

This will return the number of unread chats.

**Comment by ital0** [comment]
Please, if you have anymore questions, feel free to ask. Currently we're working in fullspeed and probably I won't be able to answer you in real time.
